# Site settings
title: King of The Blue Hills
email: pedro@bluehillscycling.com
description: Road Cycling, Mountain Biking and Cyclocross in the Greater Boston Area
  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bluehillscycling.github.io" # the base hostname & protocol for your site
twitter_username: pewerner
github_username:  pewerner

# Build settings
markdown: kramdown
paginate: 3

gems: [jekyll-paginate]

